stages:
  - build

.build:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

include:
  - local: '/kafka/.gitlab-ci.kafka.yml'
  - local: '/spark/.gitlab-ci.spark.yml'
