apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgImF1dGgiOiJaMmwwYkdGaUsyUmxjR3h2ZVMxMGIydGxiaTB6TlRNNU9EY3lPbEp4ZGxWUk9EaGFOMHRLWVVZNGRGQmpiMTl4IgogICAgCX0KICAgIH0KfQ=="

---

apiVersion: apps/v1 
kind: Deployment 
metadata: 
   name: producer-depl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: producer-depl
  template: 
    metadata: 
      labels: 
        app: producer-depl  
    spec: 
      containers:
        - name: producer
          image: registry.gitlab.com/viviane.qian/projet-sdtd/producer
          ports: 
            - containerPort: 9092
          envFrom:
          - configMapRef:
              name: producer-configmap
      imagePullSecrets:
        - name: registry-credentials